### PR TITLE
fix(container): Fixed 'unrecognised option --enableFreeMonitoring' error as it is deprecated and no longer available

### PR DESCRIPTION
**Pull request by lilian-pouliquen**
Fix proposition for #87:

I removed the options related to free monitoring in `/usr/bin/container` and added a comment on the README beside the envs to mention that it is not available for MongoDB > 4.4.

I hope it will help,
Thank you !

### CODE REVIEW

**Comment by tboerger** [comment]
It would help if you are using the right base branch which is master :)

**Comment by lilian-pouliquen** [comment]
Okay sorry, I already changed because of the branch protection.
I will change that back!

Thank you :D

**Comment by tboerger** [comment]
Please remove the variables from `v5.0/overlay/etc/entrypoint.d/05-base.sh` and `v6.0/overlay/etc/entrypoint.d/05-base.sh` as well, after that I can finally merge the PR.

Thank you for the report and the effort put into this!

**Comment by lilian-pouliquen** [comment]
It is pushed!
I really like this docker image as it is very configurable without any config file, so it is worth to help you to maintain it

Thank you for your time

**Pull request merged**
